### PR TITLE
Reload locale bundle for size and scale when locale changes

### PR DESCRIPTION
**Pull request by 3rdvision**
| - | - |
| --- | --- |
| Issue | When visiting [white](https://ripe-white-now.platforme.com/?brand=swear&model=vyner&locale=en&p=lining%3Acalf_lining%3Awhite&p=front%3Anappa%3Awhite&p=side%3Anappa%3Awhite&p=sole%3Arubber%3Awhite&p=laces%3Anylon%3Awhite&p=logo%3Ametal%3Asilver&p=hardware%3Ametal%3Asilver&p=shadow%3Adefault%3Adefault) with parameters `&locale=en` instead of proper `&locale=en_us` it will change locale to `en_us` but it won't reload the size and scale bundle locales which results in this (see image) <br> image  |
| Decisions | Loading size and locale bundles at every `pre_set_locale` event. <br> - Using `setInterval` to await ripe object being present in `ripeProvider`. |
| Animated GIF | image |

### CODE REVIEW

**Comment by 3rdvision** [comment]
@ripe-bot activity reset

**Comment by joamag** [comment]
@3rdvision let's schedule one more quick meeting with me just to close this one (finally) :)
You can now make use of calendly to schedule it :) https://calendly.com/joao-platforme/code-review

**Comment by joamag** [comment]
@3rdvision please check if the current solution works

**Comment by 3rdvision** [comment]
> @3rdvision please check if the current solution works

@joamag It's working 👍 
Needed two small fixes but it's now good to go.

**Comment by 3rdvision** [comment]
> Can you please re-test this one with the loaded event on the plugin

It's working with `loaded` pluginus event. :+1:

**Review by joamag — APPROVED** [review]

**Pull request merged**
