### PR TITLE
#972 Add section-expandable component

### PR DESCRIPTION
**Pull request by 3rdvision**
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/972 |
| Decisions | - Add section-expandable inspired by https://github.com/ripe-tech/ripe-components-vue/blob/master/vue/components/ui/molecules/section-expandable/section-expandable.vue |
| Animated GIF | Below |

https://user-images.githubusercontent.com/24736423/157859495-c524f035-276c-44dd-b834-6134b5d2b4b7.mov

### CODE REVIEW

**Review by BeeMargarida — COMMENTED** [review]
@3rdvision There should be funcionality parity between this one and the one in components-vue, so there might be a need to backport some of the things present here to the one in components-vue.

**Review by BeeMargarida — APPROVED** [review]

**Comment by BeeMargarida** [comment]
Also, here I go again with this question, but does this require being in commons-pluginus?

**Comment by 3rdvision** [comment]
> @3rdvision There should be funcionality parity between this one and the one in components-vue, so there might be a need to backport some of the things present here to the one in components-vue.

Ok but this is more of a visual adaptation and the animations are also different so they're kinda incompatible to be ported around without much work even thought the behavior is very similar.

**Comment by 3rdvision** [comment]
> Also, here I go again with this question, but does this require being in commons-pluginus?

Because it uses Icon which is only available in commons-pluginus

**Comment by BeeMargarida** [comment]
> > @3rdvision There should be funcionality parity between this one and the one in components-vue, so there might be a need to backport some of the things present here to the one in components-vue.
> 
> Ok but this is more of a visual adaptation and the animations are also different so they're kinda incompatible to be ported around without much work even thought the behavior is very similar.

It could be a prop/variants or even the components-vue can be improved. Its just that there should be feature parity between the components. Either way, this is not the focus of this PR, but something that can come later

**Comment by BeeMargarida** [comment]
> > Also, here I go again with this question, but does this require being in commons-pluginus?
> 
> Because it uses Icon which is only available in commons-pluginus

There are also several components in white that use the icon in commons-pluginus, for example the button-icon. I don't think that is an impediment

**Comment by 3rdvision** [comment]
> > > Also, here I go again with this question, but does this require being in commons-pluginus?
> > 
> > 
> > Because it uses Icon which is only available in commons-pluginus
> 
> There are also several components in white that use the icon in commons-pluginus, for example the button-icon. I don't think that is an impediment

You're right. Since this is more general I thought it could be included in ripe-commons-pluginus but looking at ripe-commons-pluginus components I don't think it makes sense anymore. I'm moving this to white.

**Pull request closed without merging**
